general:
  # File path
  sequence_name:              ""                              # e.g. "cow-and-lady"; No impact on pipeline.
                                                              # Parameter only helps name log files.
  sequence_path:              "/PATH/TO/scene.raw"
  enable_ground_truth:        true
  ground_truth_file:          "/PATH/TO/association.txt"
  benchmark:                  false
  log_path:                   "PATH/TO/log.txt" # or "PATH/TO/LOG_DIR
  enable_render:              true                            # Will be set true if benchmark is true
  output_render_path:         ""
  enable_meshing:             false
  output_mesh_path:           ""

  # Rates
  tracking_rate:              1
  integration_rate:           1
  rendering_rate:             4
  meshing_rate:               0
  fps:                        0.0

  # Other
  drop_frames:                false
  max_frame:                  -1
  icp_threshold:              1e-5
  bilateral_filter:           false
  pyramid:                    [10, 5, 4]
  render_volume_fullsize:     false

map:
  size:                       1024
  dim:                        10.24
  t_MW_factor:                [0.501, 0.501, 0.501]

sensor:
  type:                       ""                              # e.g. "pinholecamera"; No impact on pipeline.
                                                              # Parameter only helps name log files.
  intrinsics:                 [525,525,319.5,239.5]
  downsampling_factor:        4
  T_BC:                       [1, 0, 0, 0,
                               0, 1, 0, 0,
                               0, 0, 1, 0,
                               0, 0, 0, 1]
  init_T_WB:                  [0, 0, 0, 0, 0, 0, 1]           # tx, ty, tz, qx, qy, qz, qw
  near_plane:                 0.4
  far_plane:                  4.0

voxel_impl:
  surface_boundary:           0.0
  occupancy_min_max:          [-100, 100]
  max_weight:                 100
  free_space_integr_scale:    0
  const_surface_thickness:    false  # if true, surface thickness := max_surface_thickness
  tau_min_max:                [0.06, 0.16]
  k_tau:                      0.026
  uncertainty_model:          quadratic # { linear, quadratic }
  sigma_min_max:              [0.005, 0.02]  # minimum/maximum uncertainty := 3 x sigma_min/sigma_max
  k_sigma:                    0.0016